spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      maximum-pool-size: 30
      max-lifetime: 1800000
  h2:
    console:
      enabled: true
